# AUTO GENERATED FILE - DO NOT EDIT

#' @export
dashImageGallery <- function(id=NULL, additionalClass=NULL, autoPlay=NULL, disableKeyDown=NULL, disableSwipe=NULL, disableThumbnailScroll=NULL, disableThumbnailSwipe=NULL, flickThreshold=NULL, indexSeparator=NULL, infinite=NULL, isRTL=NULL, items=NULL, lazyLoad=NULL, onBeforeSlide=NULL, onBulletClick=NULL, onClick=NULL, onErrorImageURL=NULL, onImageError=NULL, onImageLoad=NULL, onMouseLeave=NULL, onMouseOver=NULL, onPause=NULL, onPlay=NULL, onScreenChange=NULL, onSlide=NULL, onThumbnailClick=NULL, onThumbnailError=NULL, onTouchEnd=NULL, onTouchMove=NULL, onTouchStart=NULL, renderCustomControls=NULL, renderFullscreenButton=NULL, renderItem=NULL, renderLeftNav=NULL, renderPlayPauseButton=NULL, renderRightNav=NULL, renderThumbInner=NULL, showBullets=NULL, showFullscreenButton=NULL, showIndex=NULL, showNav=NULL, showPlayButton=NULL, showThumbnails=NULL, slideDuration=NULL, slideInterval=NULL, slideOnThumbnailOver=NULL, startIndex=NULL, stopPropagation=NULL, swipeThreshold=NULL, swipingTransitionDuration=NULL, thumbnailPosition=NULL, useBrowserFullscreen=NULL, useTranslate3D=NULL, useWindowKeyDown=NULL) {
    
    props <- list(id=id, additionalClass=additionalClass, autoPlay=autoPlay, disableKeyDown=disableKeyDown, disableSwipe=disableSwipe, disableThumbnailScroll=disableThumbnailScroll, disableThumbnailSwipe=disableThumbnailSwipe, flickThreshold=flickThreshold, indexSeparator=indexSeparator, infinite=infinite, isRTL=isRTL, items=items, lazyLoad=lazyLoad, onBeforeSlide=onBeforeSlide, onBulletClick=onBulletClick, onClick=onClick, onErrorImageURL=onErrorImageURL, onImageError=onImageError, onImageLoad=onImageLoad, onMouseLeave=onMouseLeave, onMouseOver=onMouseOver, onPause=onPause, onPlay=onPlay, onScreenChange=onScreenChange, onSlide=onSlide, onThumbnailClick=onThumbnailClick, onThumbnailError=onThumbnailError, onTouchEnd=onTouchEnd, onTouchMove=onTouchMove, onTouchStart=onTouchStart, renderCustomControls=renderCustomControls, renderFullscreenButton=renderFullscreenButton, renderItem=renderItem, renderLeftNav=renderLeftNav, renderPlayPauseButton=renderPlayPauseButton, renderRightNav=renderRightNav, renderThumbInner=renderThumbInner, showBullets=showBullets, showFullscreenButton=showFullscreenButton, showIndex=showIndex, showNav=showNav, showPlayButton=showPlayButton, showThumbnails=showThumbnails, slideDuration=slideDuration, slideInterval=slideInterval, slideOnThumbnailOver=slideOnThumbnailOver, startIndex=startIndex, stopPropagation=stopPropagation, swipeThreshold=swipeThreshold, swipingTransitionDuration=swipingTransitionDuration, thumbnailPosition=thumbnailPosition, useBrowserFullscreen=useBrowserFullscreen, useTranslate3D=useTranslate3D, useWindowKeyDown=useWindowKeyDown)
    if (length(props) > 0) {
        props <- props[!vapply(props, is.null, logical(1))]
    }
    component <- list(
        props = props,
        type = 'DashImageGallery',
        namespace = 'dash_image_gallery',
        propNames = c('id', 'additionalClass', 'autoPlay', 'disableKeyDown', 'disableSwipe', 'disableThumbnailScroll', 'disableThumbnailSwipe', 'flickThreshold', 'indexSeparator', 'infinite', 'isRTL', 'items', 'lazyLoad', 'onBeforeSlide', 'onBulletClick', 'onClick', 'onErrorImageURL', 'onImageError', 'onImageLoad', 'onMouseLeave', 'onMouseOver', 'onPause', 'onPlay', 'onScreenChange', 'onSlide', 'onThumbnailClick', 'onThumbnailError', 'onTouchEnd', 'onTouchMove', 'onTouchStart', 'renderCustomControls', 'renderFullscreenButton', 'renderItem', 'renderLeftNav', 'renderPlayPauseButton', 'renderRightNav', 'renderThumbInner', 'showBullets', 'showFullscreenButton', 'showIndex', 'showNav', 'showPlayButton', 'showThumbnails', 'slideDuration', 'slideInterval', 'slideOnThumbnailOver', 'startIndex', 'stopPropagation', 'swipeThreshold', 'swipingTransitionDuration', 'thumbnailPosition', 'useBrowserFullscreen', 'useTranslate3D', 'useWindowKeyDown'),
        package = 'dashImageGallery'
        )

    structure(component, class = c('dash_component', 'list'))
}
